[package]
name = "randtime"
version = "0.1.0"
authors = ["Eric Groom <egroom@mail.sfsu.edu>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
actix-files = "0.2.1"
tera = "1.0.1"
futures = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.14"
env_logger = "0.7.1"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.7"